name: badges
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  badges:
    name: Badges
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update version badges
        run: npm run badges

      - name: Commit any changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated badges
          branch: main
          file_pattern: README.md